INSERT INTO pages (title, slug, menu_title, banner_title, banner_subtitle, short_description, content, meta_title, meta_description, show_in_menu, sort_order)
VALUES
('Home','home','Home','Server Management & Cloud Infrastructure Experts','24x7x365 server management, hosting support, cloud infrastructure and software development services.','Netedge Technology provides server management, technical support, cloud infrastructure and software development services.','<h2>Welcome to Netedge Technology</h2><p>Netedge Technology delivers reliable server management, technical support, infrastructure management and software development services to businesses worldwide.</p>','Netedge Technology - Server Management & IT Infrastructure Experts','Professional server management, cloud infrastructure, technical support and software development services.',0,0),
('Company','company','Company','About Netedge Technology','A dependable IT partner for server management, infrastructure support and software development.','About Netedge Technology','<h2>About Netedge Technology</h2><p>Netedge Technology is an IT services company focused on server management, cloud infrastructure, technical support and custom software development.</p>',NULL,NULL,1,10),
('Why Us','why-us','Why Us','Why Choose Netedge Technology','Experienced, reliable and security-focused IT infrastructure support.','Why choose Netedge Technology','<h2>Why Us</h2><p>We combine technical expertise, 24x7 support and practical experience across hosting, cloud and software environments.</p>',NULL,NULL,1,20),
('Technical Support','technical-support','Technical Support','Technical Support Services','Professional technical support for hosting companies and online businesses.','Technical support services','<h2>Technical Support</h2><p>We provide technical support, ticket handling, server troubleshooting and hosting support services.</p>',NULL,NULL,1,30),
('Web Application Development','web-application-development','Web Application Development','Web Application Development','Secure, scalable and business-focused web application development.','Web application development','<h2>Web Application Development</h2><p>We build custom web applications, business portals and software platforms using practical and maintainable technologies.</p>',NULL,NULL,1,40),
('Portfolio','portfolio','Portfolio','Portfolio','A snapshot of our work and capabilities.','Portfolio','<h2>Portfolio</h2><p>Portfolio items will be managed from CMS in the next phase.</p>',NULL,NULL,1,50),
('Achievements','achievements','Achievements','Achievements','Experience and delivery metrics that reflect our technical strength.','Achievements','<h2>Achievements</h2><ul><li>1000+ Linux servers managed</li><li>600+ Windows servers managed</li><li>500+ cPanel servers managed</li><li>20000+ tickets resolved</li></ul>',NULL,NULL,1,60),
('Testimonials','testimonials','Testimonials','Testimonials','Client feedback and service experiences.','Testimonials','<h2>Testimonials</h2><p>Testimonials will be managed from CMS in the next phase.</p>',NULL,NULL,1,70),
('Career','career','Career','Careers at Netedge Technology','Build your career with a team focused on infrastructure, support and software engineering.','Careers','<h2>Careers</h2><p>Explore opportunities to work with Netedge Technology. Current openings will be managed from the jobs module.</p><p><a href="/jobs">View Current Openings</a></p>',NULL,NULL,1,80),
('Jobs','jobs','Jobs','Current Openings','Explore current job opportunities at Netedge Technology.','Jobs','<h2>Current Openings</h2><p>The dynamic jobs module will be added in Phase 2.</p>',NULL,NULL,1,90),
('Contact Us','contact-us','Contact Us','Contact Netedge Technology','Talk to us for server management, cloud infrastructure, support and software development.','Contact Netedge Technology','<h2>Contact Us</h2><p><strong>Address:</strong> 10, Amrapali Axiom, 4th Floor, Opp. Bopal Bridge, Ambli, Bopal, Ahmedabad - 380058</p><p><strong>Mobile:</strong> +91-9909777343</p><p><strong>Sales:</strong> sales@netedgetechnology.net</p><p><strong>Support:</strong> support@netedgetechnology.net</p>',NULL,NULL,1,100)
ON DUPLICATE KEY UPDATE title=VALUES(title);


INSERT INTO jobs (title, slug, department, location, job_type, experience, short_description, description, responsibilities, requirements, status, sort_order)
VALUES
('Process Associate','process-associate','Operations','Ahmedabad','Full Time','0-2 years','Support business operations, documentation and process coordination.','<p>We are looking for a Process Associate to support day-to-day operational activities and documentation.</p>','<ul><li>Handle assigned operational tasks</li><li>Maintain process documentation</li><li>Coordinate with internal teams</li></ul>','<ul><li>Good communication skills</li><li>Basic computer knowledge</li><li>Attention to detail</li></ul>','active',10),
('Quality Analyst','quality-analyst','Quality','Ahmedabad','Full Time','1-3 years','Monitor quality, review processes and help improve service delivery.','<p>Quality Analyst will review support/service processes and help maintain delivery standards.</p>','<ul><li>Audit tickets and processes</li><li>Prepare quality reports</li><li>Suggest improvements</li></ul>','<ul><li>Analytical mindset</li><li>Good documentation skills</li><li>Experience in IT support preferred</li></ul>','active',20),
('Sr. IOS Developer','sr-ios-developer','Software Development','Ahmedabad','Full Time','3+ years','Develop and maintain iOS applications for business and client projects.','<p>We are looking for an experienced iOS developer for mobile application development projects.</p>','<ul><li>Build iOS applications</li><li>Work with APIs</li><li>Maintain code quality</li></ul>','<ul><li>Swift / Objective-C experience</li><li>App Store deployment knowledge</li><li>Strong debugging skills</li></ul>','active',30),
('Technical Project Manager','technical-project-manager','Project Management','Ahmedabad','Full Time','5+ years','Manage technical projects, teams, timelines and client communication.','<p>Technical Project Manager will coordinate software and infrastructure projects from planning to delivery.</p>','<ul><li>Manage project timelines</li><li>Coordinate with developers/admins</li><li>Communicate with clients</li></ul>','<ul><li>Strong technical understanding</li><li>Project management experience</li><li>Excellent communication</li></ul>','active',40),
('UI Designer','ui-designer','Design','Ahmedabad','Full Time','1-3 years','Create clean, professional and user-friendly web/mobile interfaces.','<p>We need a UI Designer with a strong sense of layout, typography and modern interface design.</p>','<ul><li>Create website/app designs</li><li>Prepare design assets</li><li>Work with frontend team</li></ul>','<ul><li>Figma/Adobe XD knowledge</li><li>Portfolio required</li><li>Good visual design sense</li></ul>','active',50),
('Cloud Administrator','cloud-administrator','Infrastructure','Ahmedabad','Full Time','2+ years','Manage cloud servers, monitoring, backups, security and infrastructure tasks.','<p>Cloud Administrator will manage cloud infrastructure and support server operations.</p>','<ul><li>Manage cloud instances</li><li>Monitor uptime and performance</li><li>Handle backups and security</li></ul>','<ul><li>Linux knowledge</li><li>AWS/Azure/cloud experience preferred</li><li>Troubleshooting skills</li></ul>','active',60),
('UI Front End Developer','ui-front-end-developer','Software Development','Ahmedabad','Full Time','1-3 years','Convert modern designs into responsive HTML/CSS/JS interfaces.','<p>Frontend developer will build responsive user interfaces for websites and applications.</p>','<ul><li>Develop responsive pages</li><li>Optimize UI performance</li><li>Coordinate with designers</li></ul>','<ul><li>HTML/CSS/JavaScript</li><li>Bootstrap/Tailwind knowledge</li><li>Responsive design experience</li></ul>','active',70),
('ReactJS Developer','reactjs-developer','Software Development','Ahmedabad','Full Time','2+ years','Build modern ReactJS interfaces and frontend applications.','<p>ReactJS Developer will work on modern web application frontend development.</p>','<ul><li>Build React components</li><li>Integrate APIs</li><li>Maintain frontend code</li></ul>','<ul><li>ReactJS experience</li><li>JavaScript/TypeScript knowledge</li><li>State management understanding</li></ul>','active',80),
('Linux Server Administrator','linux-server-administrator','Infrastructure','Ahmedabad','Full Time','2+ years','Manage Linux servers, hosting panels, security, monitoring and troubleshooting.','<p>Linux Server Administrator will manage Linux hosting and server environments.</p>','<ul><li>Server monitoring</li><li>Security hardening</li><li>Troubleshooting server issues</li></ul>','<ul><li>Linux administration</li><li>cPanel/Plesk knowledge preferred</li><li>Shell basics</li></ul>','active',90),
('Android Developer','android-developer','Software Development','Ahmedabad','Full Time','2+ years','Develop and maintain Android mobile applications.','<p>Android Developer will work on native mobile application development.</p>','<ul><li>Build Android apps</li><li>Integrate APIs</li><li>Fix bugs and improve performance</li></ul>','<ul><li>Kotlin/Java experience</li><li>Android Studio knowledge</li><li>API integration experience</li></ul>','active',100),
('Jr. Windows System Admin','jr-windows-system-admin','Infrastructure','Ahmedabad','Full Time','0-2 years','Assist with Windows server support, monitoring and troubleshooting.','<p>Junior Windows System Admin will support Windows server administration tasks.</p>','<ul><li>Monitor Windows servers</li><li>Assist with troubleshooting</li><li>Maintain documentation</li></ul>','<ul><li>Windows Server basics</li><li>Good troubleshooting approach</li><li>Willingness to learn</li></ul>','active',110),
('Marketing Manager','marketing-manager','Marketing','Ahmedabad','Full Time','3+ years','Plan and execute marketing activities for IT services and lead generation.','<p>Marketing Manager will support lead generation, campaigns and business growth activities.</p>','<ul><li>Plan campaigns</li><li>Coordinate digital marketing</li><li>Track leads and performance</li></ul>','<ul><li>IT services marketing experience preferred</li><li>Good communication</li><li>Lead generation knowledge</li></ul>','active',120),
('.Net Developer','dot-net-developer','Software Development','Ahmedabad','Full Time','1-3 years','Develop .NET applications and business software modules.','<p>.NET Developer will work on application development and maintenance.</p>','<ul><li>Develop .NET modules</li><li>Work with databases</li><li>Fix bugs and improve code</li></ul>','<ul><li>C#/.NET knowledge</li><li>SQL Server basics</li><li>Good coding practices</li></ul>','active',130),
('Sr. Net Developer','sr-net-developer','Software Development','Ahmedabad','Full Time','4+ years','Lead .NET development tasks and mentor junior developers.','<p>Senior .NET Developer will handle complex modules and guide development work.</p>','<ul><li>Develop and review code</li><li>Design modules</li><li>Mentor junior developers</li></ul>','<ul><li>Strong C#/.NET experience</li><li>Database design knowledge</li><li>API development experience</li></ul>','active',140),
('UX Designer','ux-designer','Design','Ahmedabad','Full Time','2+ years','Design user journeys, wireframes and user-friendly product experiences.','<p>UX Designer will improve usability and structure for websites and applications.</p>','<ul><li>Create wireframes</li><li>Plan user flows</li><li>Work with UI/development teams</li></ul>','<ul><li>UX process knowledge</li><li>Figma/Adobe XD</li><li>Portfolio preferred</li></ul>','active',150),
('PHP Programmer','php-programmer','Software Development','Ahmedabad','Full Time','1-3 years','Develop PHP websites, applications and CMS modules.','<p>PHP Programmer will work on PHP/MySQL websites and application modules.</p>','<ul><li>Develop PHP modules</li><li>Work with MySQL</li><li>Maintain existing applications</li></ul>','<ul><li>PHP/MySQL knowledge</li><li>HTML/CSS/JS basics</li><li>Secure coding understanding</li></ul>','active',160),
('Jr. Linux Server Administrator','jr-linux-server-administrator','Infrastructure','Ahmedabad','Full Time','0-2 years','Assist with Linux server monitoring, support and basic administration.','<p>Junior Linux Server Administrator will support server management activities.</p>','<ul><li>Monitor servers</li><li>Assist with tickets</li><li>Learn server administration</li></ul>','<ul><li>Linux basics</li><li>Good learning attitude</li><li>Basic networking knowledge</li></ul>','active',170),
('Sr. PHP Developer','sr-php-developer','Software Development','Ahmedabad','Full Time','4+ years','Lead PHP development, architecture and secure application coding.','<p>Senior PHP Developer will handle advanced PHP/MySQL development work.</p>','<ul><li>Develop secure PHP applications</li><li>Review code</li><li>Guide junior developers</li></ul>','<ul><li>Strong PHP/MySQL experience</li><li>API development</li><li>Security-focused coding</li></ul>','active',180)
ON DUPLICATE KEY UPDATE title=VALUES(title);


INSERT INTO achievements (metric,label,status,sort_order) VALUES
('15+','Years Experience','enabled',10),
('24x7','Technical Support','enabled',20),
('1000+','Linux Servers Managed','enabled',30),
('600+','Windows Servers Managed','enabled',40),
('500+','cPanel Servers Managed','enabled',50),
('20000+','Tickets Resolved','enabled',60)
ON DUPLICATE KEY UPDATE label=VALUES(label);

INSERT INTO testimonials (client_name, client_company, message, status, sort_order) VALUES
('Hosting Partner','Web Hosting Company','Netedge Technology has been a dependable technical support partner for server and hosting operations.','enabled',10),
('Infrastructure Client','Cloud Services Business','Their team understands server management, troubleshooting and uptime requirements very well.','enabled',20),
('Software Client','Business Application Project','Netedge helped us with practical development and reliable technical execution.','enabled',30);

INSERT INTO portfolio_items (title, description, status, sort_order) VALUES
('Server Management Operations','Linux, Windows, cPanel and Plesk server management for hosting and business environments.','enabled',10),
('Cloud Infrastructure Support','Cloud server setup, migration, monitoring and ongoing infrastructure administration.','enabled',20),
('Custom Web Applications','Business web applications, portals and custom PHP/MySQL software solutions.','enabled',30),
('Technical Support Desk','Ticket handling, hosting support and NOC-style support services for online businesses.','enabled',40);

INSERT INTO settings (setting_key, setting_value) VALUES
('site_name','Netedge Technology'),
('contact_email','sales@netedgetechnology.net'),
('support_email','support@netedgetechnology.net'),
('contact_phone','+91-9909777343')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);
