INSERT INTO pages (title, slug, menu_title, banner_title, banner_subtitle, short_description, content, meta_title, meta_description, show_in_menu, sort_order)
VALUES
('Home','home','Home','Server Management & Cloud Infrastructure Experts','24x7x365 server management, hosting support, cloud infrastructure and software development services.','Netedge Technology provides server management, technical support, cloud infrastructure and software development services.','<h2>Welcome to Netedge Technology</h2><p>Netedge Technology delivers reliable server management, technical support, infrastructure management and software development services to businesses worldwide.</p>','Netedge Technology - Server Management & IT Infrastructure Experts','Professional server management, cloud infrastructure, technical support and software development services.',0,0),
('Company','company','Company','About Netedge Technology','A dependable IT partner for server management, infrastructure support and software development.','About Netedge Technology','<h2>About Netedge Technology</h2><p>Netedge Technology is an IT services company focused on server management, cloud infrastructure, technical support and custom software development.</p>',NULL,NULL,1,10),
('Why Us','why-us','Why Us','Why Choose Netedge Technology','Experienced, reliable and security-focused IT infrastructure support.','Why choose Netedge Technology','<h2>Why Us</h2><p>We combine technical expertise, 24x7 support and practical experience across hosting, cloud and software environments.</p>',NULL,NULL,1,20),
('Technical Support','technical-support','Technical Support','Technical Support Services','Professional technical support for hosting companies and online businesses.','Technical support services','<h2>Technical Support</h2><p>We provide technical support, ticket handling, server troubleshooting and hosting support services.</p>',NULL,NULL,1,30),
('Web Application Development','web-application-development','Web Application Development','Web Application Development','Secure, scalable and business-focused web application development.','Web application development','<h2>Web Application Development</h2><p>We build custom web applications, business portals and software platforms using practical and maintainable technologies.</p>',NULL,NULL,1,40),
('Portfolio','portfolio','Portfolio','Portfolio','A snapshot of our work and capabilities.','Portfolio','<h2>Portfolio</h2><p>Portfolio items will be managed from CMS in the next phase.</p>',NULL,NULL,1,50),
('Achievements','achievements','Achievements','Achievements','Experience and delivery metrics that reflect our technical strength.','Achievements','<h2>Achievements</h2><ul><li>1000+ Linux servers managed</li><li>600+ Windows servers managed</li><li>500+ cPanel servers managed</li><li>20000+ tickets resolved</li></ul>',NULL,NULL,1,60),
('Testimonials','testimonials','Testimonials','Testimonials','Client feedback and service experiences.','Testimonials','<h2>Testimonials</h2><p>Testimonials will be managed from CMS in the next phase.</p>',NULL,NULL,1,70),
('Career','career','Career','Careers at Netedge Technology','Build your career with a team focused on infrastructure, support and software engineering.','Careers','<h2>Careers</h2><p>Explore opportunities to work with Netedge Technology. Current openings will be managed from the jobs module.</p><p><a href="/jobs">View Current Openings</a></p>',NULL,NULL,1,80),
('Jobs','jobs','Jobs','Current Openings','Explore current job opportunities at Netedge Technology.','Jobs','<h2>Current Openings</h2><p>The dynamic jobs module will be added in Phase 2.</p>',NULL,NULL,1,90),
('Contact Us','contact-us','Contact Us','Contact Netedge Technology','Talk to us for server management, cloud infrastructure, support and software development.','Contact Netedge Technology','<h2>Contact Us</h2><p><strong>Address:</strong> 10, Amrapali Axiom, 4th Floor, Opp. Bopal Bridge, Ambli, Bopal, Ahmedabad - 380058</p><p><strong>Mobile:</strong> +91-9909777343</p><p><strong>Sales:</strong> sales@netedgetechnology.net</p><p><strong>Support:</strong> support@netedgetechnology.net</p>',NULL,NULL,1,100)
ON DUPLICATE KEY UPDATE title=VALUES(title);
